name: deployment

# Controls when the action will run. Triggers the workflow on push event, but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the project
        run: |
          cd app
          npm install
          npm run build
      
      - name: Sync
        env:
          dest: '${{secrets.DEPLOY_USER}}@${{secrets.DEPLOY_SERVER}}:${{secrets.DEPLOY_DIR}}'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > DEPLOY_KEY_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./ ${{env.dest}}
